// Board items — CRUD against the polymorphic Item table for the
// canonical studio-item flavor. The Item model's `(itemType, itemId)`
// pair points to whichever entity backs the row; for studio-item
// boards `itemType = "studio-item"` and we mint our own `itemId`
// (cuid generated by Prisma — we use a synthetic cuid here so the
// unique constraint holds).
//
// Row data layout:
//   item.title    — the hoisted Title cell (always present)
//   item.status   — the hoisted Status cell (single-select string)
//   item.ownerId  — assignee user id (nullable)
//   item.metadata — JSON map for any other column values (Phase 3c
//                   field shelf writes here)
//
// Default status palette (used when Board.schema.fields doesn't yet
// define one — Phase 3c will override per-board):
//   TO_DO        slate
//   IN_PROGRESS  blue
//   DONE         green

import { prisma } from "@/lib/prisma";
import { logActivity } from "@/lib/item-thread";
import { DEFAULT_STATUS_OPTIONS, type BoardItemRow } from "@/lib/board-items-shared";

// Re-export the client-safe pieces so existing server code (API routes,
// page server components) keeps working with `from "@/lib/board-items"`.
// Client components must import from `@/lib/board-items-shared` directly
// to avoid pulling Prisma + pg into the browser bundle.
export { DEFAULT_STATUS_OPTIONS, type BoardItemRow };

function rowFrom(it: {
  id: string;
  title: string;
  status: string | null;
  ownerId: string | null;
  groupKey: string | null;
  position: number;
  metadata: unknown;
  archivedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
}, owner?: { id: string; firstName: string; lastName: string; avatar: string | null } | null): BoardItemRow {
  return {
    id: it.id,
    title: it.title,
    status: it.status,
    ownerId: it.ownerId,
    groupKey: it.groupKey,
    position: it.position,
    metadata: (it.metadata as Record<string, unknown>) ?? {},
    archivedAt: it.archivedAt,
    createdAt: it.createdAt,
    updatedAt: it.updatedAt,
    owner: owner ?? null,
  };
}

export async function listBoardItems(boardId: string, opts: { includeArchived?: boolean } = {}): Promise<BoardItemRow[]> {
  const rows = await prisma.item.findMany({
    where: {
      boardId,
      ...(opts.includeArchived ? {} : { archivedAt: null }),
    },
    orderBy: { position: "asc" },
  });

  // Fetch owners in one batch — N+1 protection.
  const ownerIds = Array.from(new Set(rows.map((r) => r.ownerId).filter((x): x is string => !!x)));
  const owners = ownerIds.length
    ? await prisma.user.findMany({
        where: { id: { in: ownerIds } },
        select: { id: true, firstName: true, lastName: true, avatar: true },
      })
    : [];
  const ownerById = new Map(owners.map((o) => [o.id, o] as const));

  return rows.map((r) => rowFrom(r, r.ownerId ? ownerById.get(r.ownerId) ?? null : null));
}

export interface CreateBoardItemInput {
  organizationId: string;
  boardId: string;
  title: string;
  status?: string;
  ownerId?: string;
  groupKey?: string;
  metadata?: Record<string, unknown>;
  /** Logged on the activity feed for this item. Pass the session
   *  user's id; null only for system-generated rows. */
  actorId?: string | null;
}

/**
 * Append a new item to the end of a board. Position = max + 1024 to
 * preserve room for fractional inserts later. Generates a synthetic
 * itemId so the unique (itemType, itemId) constraint holds.
 */
export async function createBoardItem(input: CreateBoardItemInput): Promise<BoardItemRow> {
  const trimmed = input.title.trim();
  if (!trimmed) throw new Error("Title is required");

  const last = await prisma.item.findFirst({
    where: { boardId: input.boardId },
    orderBy: { position: "desc" },
    select: { position: true },
  });
  const position = (last?.position ?? 0) + 1024;

  // Synthetic itemId — for studio-item rows the Item row IS the row;
  // there's no separate canonical entity table. We use the row's own
  // id so itemId == id; the unique constraint becomes per-row.
  const id = cuid();
  const created = await prisma.item.create({
    data: {
      id,
      organizationId: input.organizationId,
      boardId: input.boardId,
      itemType: "studio-item",
      itemId: id,
      title: trimmed,
      status: input.status ?? "TO_DO",
      ownerId: input.ownerId ?? null,
      groupKey: input.groupKey ?? null,
      position,
      metadata: (input.metadata ?? {}) as object,
    },
  });
  const owner = input.ownerId
    ? await prisma.user.findUnique({
        where: { id: input.ownerId },
        select: { id: true, firstName: true, lastName: true, avatar: true },
      })
    : null;

  await logActivity({
    organizationId: input.organizationId,
    itemId: created.id,
    actorId: input.actorId ?? null,
    action: "CREATED",
    meta: { title: trimmed, status: created.status },
  });

  return rowFrom(created, owner);
}

export interface UpdateBoardItemInput {
  title?: string;
  status?: string | null;
  ownerId?: string | null;
  groupKey?: string | null;
  position?: number;
  metadata?: Record<string, unknown>;
}

export async function updateBoardItem(
  itemId: string,
  patch: UpdateBoardItemInput,
  actorId: string | null = null,
): Promise<BoardItemRow> {
  // Capture the pre-edit values so we can diff for the activity log.
  const before = await prisma.item.findUnique({
    where: { id: itemId },
    select: { organizationId: true, title: true, status: true, ownerId: true },
  });

  const data: Record<string, unknown> = {};
  if (patch.title !== undefined) {
    const trimmed = patch.title.trim();
    if (!trimmed) throw new Error("Title cannot be empty");
    data.title = trimmed;
  }
  if (patch.status !== undefined) data.status = patch.status;
  if (patch.ownerId !== undefined) data.ownerId = patch.ownerId;
  if (patch.groupKey !== undefined) data.groupKey = patch.groupKey;
  if (patch.position !== undefined) data.position = patch.position;
  if (patch.metadata !== undefined) data.metadata = patch.metadata as object;

  const updated = await prisma.item.update({ where: { id: itemId }, data });
  const owner = updated.ownerId
    ? await prisma.user.findUnique({
        where: { id: updated.ownerId },
        select: { id: true, firstName: true, lastName: true, avatar: true },
      })
    : null;

  if (before) {
    if (patch.title !== undefined && before.title !== updated.title) {
      await logActivity({
        organizationId: before.organizationId,
        itemId,
        actorId,
        action: "TITLE_CHANGED",
        meta: { from: before.title, to: updated.title },
      });
    }
    if (patch.status !== undefined && before.status !== updated.status) {
      await logActivity({
        organizationId: before.organizationId,
        itemId,
        actorId,
        action: "STATUS_CHANGED",
        meta: { from: before.status, to: updated.status },
      });
    }
    if (patch.ownerId !== undefined && before.ownerId !== updated.ownerId) {
      await logActivity({
        organizationId: before.organizationId,
        itemId,
        actorId,
        action: "OWNER_CHANGED",
        meta: { from: before.ownerId, to: updated.ownerId },
      });
    }
    if (patch.metadata !== undefined) {
      await logActivity({
        organizationId: before.organizationId,
        itemId,
        actorId,
        action: "FIELDS_UPDATED",
        meta: {},
      });
    }
  }

  return rowFrom(updated, owner);
}

export async function archiveBoardItem(itemId: string, actorId: string | null = null): Promise<BoardItemRow> {
  const updated = await prisma.item.update({
    where: { id: itemId },
    data: { archivedAt: new Date() },
  });
  await logActivity({
    organizationId: updated.organizationId,
    itemId,
    actorId,
    action: "ARCHIVED",
    meta: {},
  });
  return rowFrom(updated);
}

export async function deleteBoardItem(itemId: string): Promise<void> {
  await prisma.item.delete({ where: { id: itemId } });
}

// ── Internal: cuid (Prisma's cuid v1 algorithm without the dep) ──
//
// We generate the row's own primary key client-side here because we
// also write it into the polymorphic `itemId` column to satisfy the
// (itemType, itemId) unique constraint. Prisma's @default(cuid()) only
// fires on auto-generated PKs, so we mirror its behavior in TS.
function cuid(): string {
  const ts = Date.now().toString(36);
  const r = Array.from({ length: 16 }, () =>
    Math.floor(Math.random() * 36).toString(36),
  ).join("");
  return `c${ts}${r}`.slice(0, 25);
}
