// Board items — CRUD against the polymorphic Item table for the
// canonical studio-item flavor. The Item model's `(itemType, itemId)`
// pair points to whichever entity backs the row; for studio-item
// boards `itemType = "studio-item"` and we mint our own `itemId`
// (cuid generated by Prisma — we use a synthetic cuid here so the
// unique constraint holds).
//
// Row data layout:
//   item.title    — the hoisted Title cell (always present)
//   item.status   — the hoisted Status cell (single-select string)
//   item.ownerId  — assignee user id (nullable)
//   item.metadata — JSON map for any other column values (Phase 3c
//                   field shelf writes here)
//
// Default status palette (used when Board.schema.fields doesn't yet
// define one — Phase 3c will override per-board):
//   TO_DO        slate
//   IN_PROGRESS  blue
//   DONE         green

import { prisma } from "@/lib/prisma";
import { logActivity } from "@/lib/item-thread";
import { changedMetadataKeys, sameIdList, sameTime, sameValue } from "@/lib/item-diff";
import { parseRecurrence } from "@/lib/recurrence";
import { withArchivedBy, clearArchivedBy } from "@/lib/archived-by";
import {
  DEFAULT_STATUS_OPTIONS,
  PRIORITY_OPTIONS,
  applyOwnerOnlyPatch,
  getBoardStatuses,
  isDoneStatus,
  makeStatusLookup,
  parseBoardStatuses,
  type BoardItemRow,
  type ItemTag,
  type StatusGroup,
  type StatusOption,
} from "@/lib/board-items-shared";
import { remapDescendantStatuses } from "@/lib/item-move";

// Re-export the client-safe pieces so existing server code (API routes,
// page server components) keeps working with `from "@/lib/board-items"`.
// Client components must import from `@/lib/board-items-shared` directly
// to avoid pulling Prisma + pg into the browser bundle.
export {
  DEFAULT_STATUS_OPTIONS,
  PRIORITY_OPTIONS,
  applyOwnerOnlyPatch,
  getBoardStatuses,
  isDoneStatus,
  makeStatusLookup,
  parseBoardStatuses,
  type BoardItemRow,
  type ItemTag,
  type StatusGroup,
  type StatusOption,
};

function rowFrom(it: {
  id: string;
  boardId?: string | null;
  title: string;
  status: string | null;
  ownerId: string | null;
  assigneeIds?: string[];
  groupKey: string | null;
  position: number;
  metadata: unknown;
  startAt?: Date | null;
  dueAt?: Date | null;
  priority?: string | null;
  itemTypeId?: string | null;
  parentItemId?: string | null;
  recurRule?: unknown;
  recurNextAt?: Date | null;
  archivedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
}, owner?: { id: string; firstName: string; lastName: string; avatar: string | null } | null, tags?: ItemTag[], spaceId?: string | null): BoardItemRow {
  return {
    id: it.id,
    // boardId + spaceId MUST survive here: the detail drawer/page overwrite
    // their cached item with this object after every PATCH/POST. Dropping them
    // (the old bug) made the *first* edit blank out boardId → subtask-add and
    // attachment widgets silently died until a full reload.
    boardId: it.boardId ?? null,
    spaceId: spaceId ?? null,
    title: it.title,
    status: it.status,
    ownerId: it.ownerId,
    assigneeIds: it.assigneeIds ?? (it.ownerId ? [it.ownerId] : []),
    groupKey: it.groupKey,
    position: it.position,
    metadata: (it.metadata as Record<string, unknown>) ?? {},
    startAt: it.startAt ?? null,
    dueAt: it.dueAt ?? null,
    priority: it.priority ?? null,
    itemTypeId: it.itemTypeId ?? null,
    parentItemId: it.parentItemId ?? null,
    recurRule: parseRecurrence(it.recurRule),
    recurNextAt: it.recurNextAt ?? null,
    archivedAt: it.archivedAt,
    createdAt: it.createdAt,
    updatedAt: it.updatedAt,
    owner: owner ?? null,
    tags: tags ?? [],
  };
}

const VALID_PRIORITIES = new Set<string>(PRIORITY_OPTIONS.map((p) => p.value));

function normalizePriority(value: string | null | undefined): string | null {
  if (value == null) return null;
  const up = value.toUpperCase();
  if (!VALID_PRIORITIES.has(up)) throw new Error(`Invalid priority: ${value}`);
  return up;
}

/** Batched tag fetch for a set of items → Map(itemId → ItemTag[]). */
async function tagsForItems(itemIds: string[]): Promise<Map<string, ItemTag[]>> {
  const map = new Map<string, ItemTag[]>();
  if (!itemIds.length) return map;
  const assignments = await prisma.tagAssignment.findMany({
    where: { entityType: "BOARD_ITEM", entityId: { in: itemIds } },
    include: { tag: { select: { id: true, name: true, color: true, archived: true } } },
    orderBy: { createdAt: "asc" },
  });
  for (const a of assignments) {
    if (a.tag.archived) continue;
    const list = map.get(a.entityId) ?? [];
    list.push({ id: a.tag.id, name: a.tag.name, color: a.tag.color });
    map.set(a.entityId, list);
  }
  return map;
}

/** Diff-sync an item's BOARD_ITEM TagAssignments to exactly `tagIds`. */
async function syncItemTags(
  organizationId: string,
  itemId: string,
  tagIds: string[],
  actorId: string | null,
): Promise<ItemTag[]> {
  // Only org-owned, non-archived tags are assignable.
  const valid = tagIds.length
    ? await prisma.tag.findMany({
        where: { organizationId, id: { in: tagIds }, archived: false },
        select: { id: true, name: true, color: true },
      })
    : [];
  const validIds = new Set(valid.map((t) => t.id));

  const existing = await prisma.tagAssignment.findMany({
    where: { entityType: "BOARD_ITEM", entityId: itemId },
    select: { id: true, tagId: true },
  });
  const existingByTag = new Map(existing.map((e) => [e.tagId, e.id] as const));

  const toAdd = [...validIds].filter((id) => !existingByTag.has(id));
  const toRemove = existing.filter((e) => !validIds.has(e.tagId));

  await Promise.all([
    toAdd.length
      ? prisma.tagAssignment.createMany({
          data: toAdd.map((tagId) => ({
            tagId,
            entityType: "BOARD_ITEM" as const,
            entityId: itemId,
            organizationId,
            assignedById: actorId,
          })),
          skipDuplicates: true,
        })
      : Promise.resolve(null),
    toRemove.length
      ? prisma.tagAssignment.deleteMany({ where: { id: { in: toRemove.map((e) => e.id) } } })
      : Promise.resolve(null),
  ]);

  // Keep the caller's requested order where possible.
  const byId = new Map(valid.map((t) => [t.id, t] as const));
  return tagIds.filter((id) => byId.has(id)).map((id) => byId.get(id)!);
}

/** The Prisma Item row fields enrichment needs — what findMany/findUnique return. */
type ItemSource = Parameters<typeof rowFrom>[0] & { id: string; ownerId: string | null };

/**
 * Enrich raw Item rows into full BoardItemRows — the ONE implementation of
 * the counts/links/time/creator decoration. listBoardItems (batch) and
 * getBoardItemRow (single) both go through here, so a single item's shape
 * can never drift from a list row's shape again (the old lean writer-return
 * silently stripped subtask/comment counts out of client caches).
 */
async function enrichItemRows(
  rows: ItemSource[],
  opts: {
    /** Precomputed direct-children counts. listBoardItems derives these from
     *  its own board fetch (no extra query); when absent we query them. */
    subtaskCountByParent?: Map<string, number>;
    /** spaceId per item id — the single-item path passes the board's spaceId. */
    spaceIdByItem?: Map<string, string | null>;
  } = {},
): Promise<BoardItemRow[]> {
  const itemIds = rows.map((r) => r.id);
  // EVERY assignee, not just the primary. The list row now renders the same
  // multi-assignee control the opened task does, and it can only show the
  // people it is given: resolving ownerId alone made a three-person task look
  // like a one-person task on the board. Same single batched query.
  const ownerIds = Array.from(
    new Set(
      rows
        .flatMap((r) => [r.ownerId, ...(r.assigneeIds ?? [])])
        .filter((x): x is string => !!x),
    ),
  );

  // Parallel batches — owners + comment counts + links (by type) + tags +
  // time-tracked sum + creator activity (+ subtask counts when the caller
  // didn't already derive them). All polymorphic aggregates key off
  // (entityType/entityId or sourceType/sourceId) via groupBy, so no N+1.
  const [owners, commentGroups, linkGroups, tagsById, timeGroups, createdActs, subtaskGroups] = await Promise.all([
    ownerIds.length
      ? prisma.user.findMany({
          where: { id: { in: ownerIds } },
          select: { id: true, firstName: true, lastName: true, avatar: true },
        })
      : Promise.resolve([] as { id: string; firstName: string; lastName: string; avatar: string | null }[]),
    itemIds.length
      ? prisma.itemUpdate.groupBy({
          by: ["entityId"],
          where: { entityType: "BOARD_ITEM", entityId: { in: itemIds } },
          _count: { _all: true },
        })
      : Promise.resolve([] as { entityId: string; _count: { _all: number } }[]),
    itemIds.length
      ? prisma.entityLink.groupBy({
          by: ["sourceId", "targetType"],
          where: { sourceType: "BOARD_ITEM", sourceId: { in: itemIds } },
          _count: { _all: true },
        })
      : Promise.resolve([] as { sourceId: string; targetType: string; _count: { _all: number } }[]),
    tagsForItems(itemIds),
    itemIds.length
      ? prisma.timerSession.groupBy({
          by: ["entityId"],
          where: { entityType: "BOARD_ITEM", entityId: { in: itemIds } },
          _sum: { durationMs: true },
        })
      : Promise.resolve([] as { entityId: string; _sum: { durationMs: number | null } }[]),
    itemIds.length
      ? prisma.itemActivity.findMany({
          where: { entityType: "BOARD_ITEM", entityId: { in: itemIds }, action: "CREATED" },
          select: { entityId: true, actorId: true },
        })
      : Promise.resolve([] as { entityId: string; actorId: string | null }[]),
    !opts.subtaskCountByParent && itemIds.length
      ? prisma.item.groupBy({
          by: ["parentItemId"],
          where: { parentItemId: { in: itemIds }, archivedAt: null },
          _count: { _all: true },
        })
      : Promise.resolve([] as { parentItemId: string | null; _count: { _all: number } }[]),
  ]);

  const ownerById = new Map(owners.map((o) => [o.id, o] as const));
  const commentCountById = new Map(commentGroups.map((g) => [g.entityId, g._count._all] as const));

  // Links split by target type — total (attachmentCount) + typed counts.
  const attachmentCountById = new Map<string, number>();
  const linkedDocById = new Map<string, number>();
  const linkedTaskById = new Map<string, number>();
  const linkedSopById = new Map<string, number>();
  for (const g of linkGroups) {
    const n = g._count._all;
    attachmentCountById.set(g.sourceId, (attachmentCountById.get(g.sourceId) ?? 0) + n);
    if (g.targetType === "DOC") linkedDocById.set(g.sourceId, n);
    else if (g.targetType === "BOARD_ITEM") linkedTaskById.set(g.sourceId, n);
    else if (g.targetType === "SOP") linkedSopById.set(g.sourceId, n);
  }
  const timeById = new Map(timeGroups.map((g) => [g.entityId, g._sum.durationMs ?? 0] as const));

  // Creator = the actor on the item's CREATED activity. Resolve any creators
  // not already in the owner batch with one extra lookup.
  const creatorIdByItem = new Map<string, string>();
  for (const a of createdActs) {
    if (a.actorId && !creatorIdByItem.has(a.entityId)) creatorIdByItem.set(a.entityId, a.actorId);
  }
  const creatorUserById = new Map(ownerById);
  const extraCreatorIds = Array.from(new Set([...creatorIdByItem.values()])).filter((id) => !creatorUserById.has(id));
  if (extraCreatorIds.length) {
    const extra = await prisma.user.findMany({
      where: { id: { in: extraCreatorIds } },
      select: { id: true, firstName: true, lastName: true, avatar: true },
    });
    for (const u of extra) creatorUserById.set(u.id, u);
  }

  // Subtask counts: the caller's precomputed map, else the batched groupBy.
  const subtaskCountByParent = opts.subtaskCountByParent
    ?? new Map(
      subtaskGroups
        .filter((g): g is typeof g & { parentItemId: string } => !!g.parentItemId)
        .map((g) => [g.parentItemId, g._count._all] as const),
    );

  return rows.map((r) => {
    const base = rowFrom(
      r,
      r.ownerId ? ownerById.get(r.ownerId) ?? null : null,
      tagsById.get(r.id) ?? [],
      opts.spaceIdByItem?.get(r.id) ?? null,
    );
    base.commentCount = commentCountById.get(r.id) ?? 0;
    base.attachmentCount = attachmentCountById.get(r.id) ?? 0;
    base.subtaskCount = subtaskCountByParent.get(r.id) ?? 0;
    base.timeTrackedMs = timeById.get(r.id) ?? 0;
    base.linkedDocCount = linkedDocById.get(r.id) ?? 0;
    base.linkedTaskCount = linkedTaskById.get(r.id) ?? 0;
    base.linkedSopCount = linkedSopById.get(r.id) ?? 0;
    // Assignees, primary first, so ownerId stays assignees[0]. A legacy row
    // with an ownerId and no assigneeIds still yields the one person.
    const people = (base.assigneeIds ?? [])
      .map((id) => ownerById.get(id))
      .filter((p): p is { id: string; firstName: string; lastName: string; avatar: string | null } => !!p);
    base.assignees = people.length ? people : base.owner ? [base.owner] : [];
    const cid = creatorIdByItem.get(r.id);
    base.createdBy = cid ? creatorUserById.get(cid) ?? null : null;
    return base;
  });
}

export async function listBoardItems(boardId: string, opts: { includeArchived?: boolean } = {}): Promise<BoardItemRow[]> {
  const rows = await prisma.item.findMany({
    where: {
      boardId,
      ...(opts.includeArchived ? {} : { archivedAt: null }),
    },
    orderBy: { position: "asc" },
  });

  // Subtask counts derived from the same fetched rows — no extra query.
  // Top-level item (parentItemId = null) gets count of its direct children.
  const subtaskCountByParent = new Map<string, number>();
  for (const r of rows) {
    if (r.parentItemId) {
      subtaskCountByParent.set(r.parentItemId, (subtaskCountByParent.get(r.parentItemId) ?? 0) + 1);
    }
  }

  return enrichItemRows(rows, { subtaskCountByParent });
}

/**
 * Enrich an already-fetched set of Item rows (GET /api/items/[id]/subtasks).
 * Same decoration as listBoardItems, so a subtask row and a List row can never
 * drift apart.
 */
export async function listBoardItemRows(rows: ItemSource[]): Promise<BoardItemRow[]> {
  return enrichItemRows(rows);
}

/**
 * One item, enriched to the exact same field coverage as a listBoardItems
 * row. API write routes respond with this so the client's optimistic caches
 * always merge a COMPLETE row — a lean writer-return here is what made rows
 * "disappear" client-side after a date/recurrence save.
 * Returns null when the item no longer exists.
 */
export async function getBoardItemRow(itemId: string): Promise<BoardItemRow | null> {
  const row = await prisma.item.findUnique({
    where: { id: itemId },
    include: { board: { select: { spaceId: true } } },
  });
  if (!row) return null;
  const [enriched] = await enrichItemRows([row], {
    spaceIdByItem: new Map<string, string | null>([[row.id, row.board.spaceId]]),
  });
  return enriched ?? null;
}

export interface CreateBoardItemInput {
  organizationId: string;
  boardId: string;
  title: string;
  status?: string;
  ownerId?: string;
  /** Multi-assignee. When given, wins over ownerId; ownerId is synced to [0]. */
  assigneeIds?: string[];
  groupKey?: string;
  metadata?: Record<string, unknown>;
  /** Phase 58 dates — ISO strings or Date; coerced before Prisma. */
  startAt?: string | Date | null;
  dueAt?: string | Date | null;
  /** Task-system phase 2 — URGENT|HIGH|NORMAL|LOW (case-insensitive). */
  priority?: string | null;
  /** Task Types — the ItemType to re-skin this row as. null = default. */
  itemTypeId?: string | null;
  /** Task-system phase 2 — workspace Tag ids to assign at create. */
  tagIds?: string[];
  /** Phase 72 — null = top-level item; set to a parent id to create a subtask. */
  parentItemId?: string | null;
  /** Logged on the activity feed for this item. Pass the session
   *  user's id; null only for system-generated rows. */
  actorId?: string | null;
}

/**
 * Normalize an assignee set: dedupe + drop empties, and keep ownerId (the
 * primary/DRI) in sync as the FIRST assignee. If assigneeIds isn't given we
 * fall back to the legacy single ownerId, so old callers still work.
 *
 * An EXPLICIT ownerId sent alongside assigneeIds is obeyed rather than
 * ignored. It used to be dropped on the floor whenever the array was
 * non-empty, so `{ assigneeIds: ["b","c"], ownerId: "c" }` answered 200 and
 * quietly made "b" the DRI. /api/items/bulk forwards both fields together, so
 * that shape reaches the writer for real. The named owner moves to the front
 * of the set; if they are not in it they are ADDED, never swapped in for
 * somebody, so no assignee the caller listed is lost either way.
 */
// The body moved to board-items-shared.ts, which imports nothing impure, and
// is re-exported here so every existing `from "@/lib/board-items"` import keeps
// working. It lived here while this file was its only caller, and that was
// enough to break CI: a unit test for a PURE function had to import this
// module, which imports the Prisma client from src/generated/prisma, which is
// generated rather than committed. It exists locally and did not resolve on a
// clean checkout, so the suite passed here and failed there. A pure function
// belongs in the pure module.
import { resolveAssignees } from "./board-items-shared";
export { resolveAssignees };

/**
 * Append a new item to the end of a board. Position = max + 1024 to
 * preserve room for fractional inserts later. Generates a synthetic
 * itemId so the unique (itemType, itemId) constraint holds.
 */
export async function createBoardItem(input: CreateBoardItemInput): Promise<BoardItemRow> {
  const trimmed = input.title.trim();
  if (!trimmed) throw new Error("Title is required");

  const createAssignees = resolveAssignees(input.assigneeIds, input.ownerId);

  // A subtask's parent MUST live on the same board (and org). Without this
  // check a caller could pass any item id and create a cross-board parent/
  // child link, which breaks the nested render (the child appears on neither
  // board's tree correctly).
  if (input.parentItemId) {
    const parent = await prisma.item.findFirst({
      where: { id: input.parentItemId, boardId: input.boardId, organizationId: input.organizationId },
      select: { id: true },
    });
    if (!parent) throw new Error("Parent task must be on the same board");
  }

  // Position scoped to the parent: subtasks order among themselves,
  // top-level items order among themselves. Otherwise creating the
  // first subtask under any parent would land at the bottom of the
  // whole board's position space.
  const last = await prisma.item.findFirst({
    where: { boardId: input.boardId, parentItemId: input.parentItemId ?? null },
    orderBy: { position: "desc" },
    select: { position: true },
  });
  const position = (last?.position ?? 0) + 1024;

  // Synthetic itemId — for studio-item rows the Item row IS the row;
  // there's no separate canonical entity table. We use the row's own
  // id so itemId == id; the unique constraint becomes per-row.
  const id = cuid();
  const created = await prisma.item.create({
    data: {
      id,
      organizationId: input.organizationId,
      boardId: input.boardId,
      itemType: "studio-item",
      itemId: id,
      title: trimmed,
      status: input.status ?? "TO_DO",
      ownerId: createAssignees.ownerId,
      assigneeIds: createAssignees.assigneeIds,
      groupKey: input.groupKey ?? null,
      position,
      startAt: input.startAt == null ? null : new Date(input.startAt),
      dueAt: input.dueAt == null ? null : new Date(input.dueAt),
      priority: normalizePriority(input.priority),
      itemTypeId: input.itemTypeId ?? null,
      metadata: (input.metadata ?? {}) as object,
      parentItemId: input.parentItemId ?? null,
    },
    include: { board: { select: { spaceId: true } } },
  });
  const tags = input.tagIds?.length
    ? await syncItemTags(input.organizationId, created.id, input.tagIds, input.actorId ?? null)
    : [];
  const owner = createAssignees.ownerId
    ? await prisma.user.findUnique({
        where: { id: createAssignees.ownerId },
        select: { id: true, firstName: true, lastName: true, avatar: true },
      })
    : null;

  await logActivity({
    organizationId: input.organizationId,
    itemId: created.id,
    actorId: input.actorId ?? null,
    action: "CREATED",
    meta: { title: trimmed, status: created.status },
  });

  // A subtask is an event on its PARENT too, and the parent's Activity tab is
  // where a reader looks for it. SUBTASK_ADDED was in the action vocabulary
  // from the start of Phase 2 and nothing wrote it.
  if (input.parentItemId) {
    await logActivity({
      organizationId: input.organizationId,
      itemId: input.parentItemId,
      actorId: input.actorId ?? null,
      action: "SUBTASK_ADDED",
      meta: { subtaskId: created.id, title: trimmed },
    });
  }

  return rowFrom(created, owner, tags, created.board.spaceId);
}

export interface UpdateBoardItemInput {
  title?: string;
  status?: string | null;
  ownerId?: string | null;
  /** Multi-assignee. When present it wins; ownerId is synced to [0]. */
  assigneeIds?: string[];
  groupKey?: string | null;
  position?: number;
  metadata?: Record<string, unknown>;
  // Phase 58 — ISO strings accepted from the API layer; coerced to Date
  // before reaching Prisma so the schema's DateTime type is happy.
  startAt?: string | Date | null;
  dueAt?: string | Date | null;
  /** Task-system phase 2 — URGENT|HIGH|NORMAL|LOW or null to clear. */
  priority?: string | null;
  /** Task Types — re-skin this row as an ItemType (null = default). */
  itemTypeId?: string | null;
  /** Task-system phase 2 — full replacement set of workspace Tag ids. */
  tagIds?: string[];
  /** Recurring tasks — the series rule ({freq,interval}) or null to stop
   *  repeating. recurNextAt is computed server-side, never set by callers. */
  recurRule?: Record<string, unknown> | null;
  /** Internal: the cron + PATCH route set the next spawn time directly. */
  recurNextAt?: Date | null;
}

export async function updateBoardItem(
  itemId: string,
  patch: UpdateBoardItemInput,
  actorId: string | null = null,
): Promise<BoardItemRow> {
  // Capture the pre-edit values so we can diff for the activity log.
  // Phase 2 (spec-task-detail section 4 step 1): the diff now covers
  // assignees, dates, type, recurrence and the metadata KEY NAMES, so the
  // Activity tab can say what changed instead of filing every save under an
  // identical, unreadable "updated fields" row.
  const before = await prisma.item.findUnique({
    where: { id: itemId },
    select: {
      organizationId: true,
      title: true,
      status: true,
      ownerId: true,
      priority: true,
      assigneeIds: true,
      startAt: true,
      dueAt: true,
      itemTypeId: true,
      recurRule: true,
      metadata: true,
    },
  });

  const data: Record<string, unknown> = {};
  if (patch.title !== undefined) {
    const trimmed = patch.title.trim();
    if (!trimmed) throw new Error("Title cannot be empty");
    data.title = trimmed;
  }
  if (patch.status !== undefined) data.status = patch.status;
  // Assignees — assigneeIds wins; either path keeps ownerId synced to [0].
  if (patch.assigneeIds !== undefined) {
    const a = resolveAssignees(patch.assigneeIds, patch.ownerId);
    data.assigneeIds = a.assigneeIds;
    data.ownerId = a.ownerId;
  } else if (patch.ownerId !== undefined) {
    // ownerId ALONE never replaces the assignee set. See applyOwnerOnlyPatch:
    // the new owner moves to the front of the people already on the task, and
    // an unassign drops only the outgoing owner. `before` already selected
    // assigneeIds/ownerId above, so this costs no extra query.
    const a = applyOwnerOnlyPatch(before?.assigneeIds, before?.ownerId, patch.ownerId);
    data.assigneeIds = a.assigneeIds;
    data.ownerId = a.ownerId;
  }
  if (patch.groupKey !== undefined) data.groupKey = patch.groupKey;
  if (patch.position !== undefined) data.position = patch.position;
  if (patch.metadata !== undefined) data.metadata = patch.metadata as object;
  if (patch.startAt !== undefined) data.startAt = patch.startAt === null ? null : new Date(patch.startAt);
  if (patch.dueAt !== undefined) data.dueAt = patch.dueAt === null ? null : new Date(patch.dueAt);
  if (patch.priority !== undefined) data.priority = normalizePriority(patch.priority);
  if (patch.itemTypeId !== undefined) data.itemTypeId = patch.itemTypeId;
  if (patch.recurRule !== undefined) data.recurRule = patch.recurRule ?? null;
  if (patch.recurNextAt !== undefined) data.recurNextAt = patch.recurNextAt;

  const updated = await prisma.item.update({
    where: { id: itemId },
    data,
    include: { board: { select: { spaceId: true } } },
  });
  const owner = updated.ownerId
    ? await prisma.user.findUnique({
        where: { id: updated.ownerId },
        select: { id: true, firstName: true, lastName: true, avatar: true },
      })
    : null;

  // The tag set BEFORE the sync, so the activity row below can tell a real
  // re-tag apart from a client re-sending the tags the task already had.
  const priorTagIds =
    patch.tagIds !== undefined
      ? ((await tagsForItems([itemId])).get(itemId) ?? []).map((t) => t.id)
      : [];
  const tags = patch.tagIds !== undefined
    ? await syncItemTags(updated.organizationId, itemId, patch.tagIds, actorId)
    : (await tagsForItems([itemId])).get(itemId) ?? [];

  if (before) {
    if (patch.title !== undefined && before.title !== updated.title) {
      await logActivity({
        organizationId: before.organizationId,
        itemId,
        actorId,
        action: "TITLE_CHANGED",
        meta: { from: before.title, to: updated.title },
      });
    }
    if (patch.status !== undefined && before.status !== updated.status) {
      await logActivity({
        organizationId: before.organizationId,
        itemId,
        actorId,
        action: "STATUS_CHANGED",
        meta: { from: before.status, to: updated.status },
      });
    }
    if (patch.ownerId !== undefined && before.ownerId !== updated.ownerId) {
      await logActivity({
        organizationId: before.organizationId,
        itemId,
        actorId,
        action: "OWNER_CHANGED",
        meta: { from: before.ownerId, to: updated.ownerId },
      });
    }
    if (patch.priority !== undefined && before.priority !== updated.priority) {
      await logActivity({
        organizationId: before.organizationId,
        itemId,
        actorId,
        action: "PRIORITY_CHANGED",
        meta: { from: before.priority, to: updated.priority },
      });
    }
    if (patch.assigneeIds !== undefined && !sameIdList(before.assigneeIds, updated.assigneeIds)) {
      await logActivity({
        organizationId: before.organizationId,
        itemId,
        actorId,
        action: "ASSIGNEES_CHANGED",
        meta: {
          added: updated.assigneeIds.filter((id) => !before.assigneeIds.includes(id)),
          removed: before.assigneeIds.filter((id) => !updated.assigneeIds.includes(id)),
        },
      });
    }
    if (patch.dueAt !== undefined && !sameTime(before.dueAt, updated.dueAt)) {
      await logActivity({
        organizationId: before.organizationId,
        itemId,
        actorId,
        action: "DUE_CHANGED",
        meta: { from: before.dueAt?.toISOString() ?? null, to: updated.dueAt?.toISOString() ?? null },
      });
    }
    if (patch.startAt !== undefined && !sameTime(before.startAt, updated.startAt)) {
      await logActivity({
        organizationId: before.organizationId,
        itemId,
        actorId,
        action: "START_CHANGED",
        meta: { from: before.startAt?.toISOString() ?? null, to: updated.startAt?.toISOString() ?? null },
      });
    }
    if (patch.itemTypeId !== undefined && before.itemTypeId !== updated.itemTypeId) {
      await logActivity({
        organizationId: before.organizationId,
        itemId,
        actorId,
        action: "TYPE_CHANGED",
        meta: { from: before.itemTypeId, to: updated.itemTypeId },
      });
    }
    // Both of these log only when the value actually MOVED. Logging on mere
    // presence of the key filed a row every time a client re-sent the tags it
    // already had, or re-saved the same recurrence rule.
    if (patch.tagIds !== undefined && !sameIdList(priorTagIds, patch.tagIds)) {
      await logActivity({
        organizationId: before.organizationId,
        itemId,
        actorId,
        action: "TAGS_CHANGED",
        meta: { to: tags.map((t) => t.name) },
      });
    }
    if (patch.recurRule !== undefined && !sameValue(before.recurRule, patch.recurRule ?? null)) {
      await logActivity({
        organizationId: before.organizationId,
        itemId,
        actorId,
        action: patch.recurRule ? "RECUR_SET" : "RECUR_CLEARED",
        meta: patch.recurRule ? { rule: patch.recurRule } : {},
      });
    }
    if (patch.metadata !== undefined) {
      // Name the keys that actually moved. An autosaving description would
      // otherwise fill the tab with identical rows nobody can read (the
      // empty-meta FIELDS_UPDATED row this replaces). When nothing moved, 
      // a re-save of the same blob, no row is written at all.
      const changed = changedMetadataKeys(before.metadata, patch.metadata);
      if (changed.length > 0) {
        await logActivity({
          organizationId: before.organizationId,
          itemId,
          actorId,
          action: "FIELDS_UPDATED",
          meta: { fields: changed },
        });
      }
    }
  }

  return rowFrom(updated, owner, tags, updated.board.spaceId);
}

export async function archiveBoardItem(itemId: string, actorId: string | null = null): Promise<BoardItemRow> {
  const updated = await withArchivedBy(actorId, (extra) =>
    prisma.item.update({
      where: { id: itemId },
      data: { archivedAt: new Date(), ...extra },
      include: { board: { select: { spaceId: true } } },
    }),
  );
  await logActivity({
    organizationId: updated.organizationId,
    itemId,
    actorId,
    action: "ARCHIVED",
    meta: {},
  });
  return rowFrom(updated, null, [], updated.board.spaceId);
}

export async function deleteBoardItem(itemId: string): Promise<void> {
  await prisma.item.delete({ where: { id: itemId } });
}

/**
 * Un-archive a task (spec-task-detail: the Archived banner's Restore, so a
 * Member never has to find the Trash page to undo their own archive).
 *
 * Idempotent: restoring a live task is a no-op that still returns the row.
 */
export async function restoreBoardItem(itemId: string, actorId: string | null = null): Promise<BoardItemRow> {
  const before = await prisma.item.findUnique({
    where: { id: itemId },
    select: { archivedAt: true },
  });
  // The archiver is cleared with the date. Leaving it behind records someone
  // as having archived a live row.
  const updated = await clearArchivedBy((extra) =>
    prisma.item.update({
      where: { id: itemId },
      data: { archivedAt: null, ...extra },
      include: { board: { select: { spaceId: true } } },
    }),
  );
  // Only a real un-archive is worth a row. A double-click, a retry or a stale
  // tab used to file a permanent "restored this task" entry for an event that
  // never happened, in a log anyone with Can view reads.
  if (before?.archivedAt) {
    await logActivity({
      organizationId: updated.organizationId,
      itemId,
      actorId,
      action: "RESTORED",
      meta: {},
    });
  }
  const owner = updated.ownerId
    ? await prisma.user.findUnique({
        where: { id: updated.ownerId },
        select: { id: true, firstName: true, lastName: true, avatar: true },
      })
    : null;
  const tags = (await tagsForItems([itemId])).get(itemId) ?? [];
  return rowFrom(updated, owner, tags, updated.board.spaceId);
}

/**
 * Move a task to another List (spec-task-detail section 4 step 1,
 * `PATCH /api/items/[id] { boardId }`).
 *
 * The caller has already gated Can edit on BOTH Lists and has already picked
 * the remapped status through `remapStatusOnMove`, the status is passed in
 * rather than computed here so the route can report it and a test can pin the
 * mapping without a database.
 *
 * `position` goes to the end of the target List, and `groupKey` follows the
 * new status so the row lands in a group that exists there. One `MOVED`
 * activity row records both Lists.
 *
 * SUBTASKS COME WITH IT. A subtask belongs to its parent, not to the List the
 * parent happened to be in: leaving the children behind split one task across
 * two Lists, showed them on the source List as top-level-looking rows whose
 * parent was elsewhere, rendered them against the wrong status palette, and
 * meant archiving the source List took the children while the parent lived on.
 * The whole tree moves in one transaction, so it can never move halfway.
 */
export async function moveBoardItem(args: {
  itemId: string;
  toBoardId: string;
  status: string | null;
  actorId: string | null;
  /** The SOURCE and TARGET status sets, so every descendant gets the same
   *  remap the parent got. Optional: a caller that omits them keeps the old
   *  behaviour (children carry their stored status across untouched). */
  fromStatuses?: readonly StatusOption[];
  toStatuses?: readonly StatusOption[];
}): Promise<BoardItemRow> {
  const before = await prisma.item.findUnique({
    where: { id: args.itemId },
    select: { boardId: true, organizationId: true, status: true, groupKey: true },
  });
  if (!before) throw new Error("Task not found");

  const last = await prisma.item.findFirst({
    where: { boardId: args.toBoardId },
    orderBy: { position: "desc" },
    select: { position: true },
  });
  const position = (last?.position ?? 0) + 1000;

  // The whole subtask tree, breadth-first from the row being moved. Bounded by
  // DESCENDANT_SWEEPS so a cycle written by an older release cannot loop here.
  const DESCENDANT_SWEEPS = 6;
  const descendants: { id: string; status: string | null }[] = [];
  let frontier = [args.itemId];
  for (let depth = 0; depth < DESCENDANT_SWEEPS && frontier.length > 0; depth += 1) {
    const kids = await prisma.item.findMany({
      where: { parentItemId: { in: frontier }, boardId: before.boardId },
      select: { id: true, status: true },
    });
    const fresh = kids.filter(
      (k) => k.id !== args.itemId && !descendants.some((d) => d.id === k.id),
    );
    frontier = fresh.map((k) => k.id);
    descendants.push(...fresh);
  }
  const descendantIds = descendants.map((d) => d.id);

  // A CHILD's status is remapped exactly like its parent's, for the reason
  // item-move.ts states: a row carrying a status the target List does not
  // declare drops out of every group-by, which looks exactly like a lost task.
  // Kanban happens to bucket an unknown status into its first column; a grouped
  // List view does not, so the child simply vanished. Grouped by REMAPPED
  // value, so the whole tree costs at most one updateMany per distinct status.
  const childStatusGroups = args.toStatuses
    ? remapDescendantStatuses(descendants, args.fromStatuses ?? [], args.toStatuses)
    : new Map<string | null, string[]>();

  const [updated] = await prisma.$transaction([
    prisma.item.update({
      where: { id: args.itemId },
      data: {
        boardId: args.toBoardId,
        status: args.status,
        // The old groupKey named a group in the OLD List. Following the status
        // is what keeps the row visible after the move; a groupKey that names
        // nothing is how a moved task "disappears" from a grouped board.
        groupKey: before.groupKey === before.status ? args.status : null,
        position,
      },
      include: { board: { select: { spaceId: true } } },
    }),
    // Subtasks follow the parent, carrying a status the target List actually
    // declares. The groupKey is cleared either way, so a row can never point at
    // a group that does not exist in the target List.
    ...(descendantIds.length > 0
      ? childStatusGroups.size > 0
        ? [...childStatusGroups.entries()].map(([status, ids]) =>
            prisma.item.updateMany({
              where: { id: { in: ids } },
              data: { boardId: args.toBoardId, groupKey: null, status },
            }),
          )
        : [
            prisma.item.updateMany({
              where: { id: { in: descendantIds } },
              data: { boardId: args.toBoardId, groupKey: null },
            }),
          ]
      : []),
  ]);

  await logActivity({
    organizationId: before.organizationId,
    itemId: args.itemId,
    actorId: args.actorId,
    action: "MOVED",
    meta: {
      fromBoardId: before.boardId,
      toBoardId: args.toBoardId,
      fromStatus: before.status,
      toStatus: args.status,
      subtasksMoved: descendantIds.length,
    },
  });

  const owner = updated.ownerId
    ? await prisma.user.findUnique({
        where: { id: updated.ownerId },
        select: { id: true, firstName: true, lastName: true, avatar: true },
      })
    : null;
  const tags = (await tagsForItems([args.itemId])).get(args.itemId) ?? [];
  return rowFrom(updated, owner, tags, updated.board.spaceId);
}

// ── Internal: cuid (Prisma's cuid v1 algorithm without the dep) ──
//
// We generate the row's own primary key client-side here because we
// also write it into the polymorphic `itemId` column to satisfy the
// (itemType, itemId) unique constraint. Prisma's @default(cuid()) only
// fires on auto-generated PKs, so we mirror its behavior in TS.
function cuid(): string {
  const ts = Date.now().toString(36);
  const r = Array.from({ length: 16 }, () =>
    Math.floor(Math.random() * 36).toString(36),
  ).join("");
  return `c${ts}${r}`.slice(0, 25);
}
