import {
  Briefcase, Building, Building2, BookOpen, Beaker, Brain, Bug,
  Calculator, Calendar, Camera, Car, ChartBar, ChartLine, ChartPie, Cloud,
  Code, Compass, Cpu, CreditCard,
  Database, DollarSign, Dumbbell,
  Factory, Flag, FileText, Film,
  Gauge, Gem, Gift, Globe, GraduationCap,
  Hammer, HardHat, Headphones, Heart, Home, Hospital,
  Image as ImageIcon, Inbox,
  Key,
  Languages, Laptop, Layers, Library, Lightbulb, Link as LinkIcon,
  MapPin, Megaphone, MessageCircle, Mic, Monitor, Mountain, Music,
  Newspaper, Notebook,
  Package, Palette, Paperclip, Pen, PenTool, Phone, Plane, Plug, Printer, Puzzle,
  Radio, Receipt, Rocket,
  Scale, Scissors, Server, Settings, Shield, ShoppingCart, Sparkles, Star, Sun,
  Target, Telescope, TestTube, Ticket, TreePine, TrendingUp, Trophy, Truck, Tv,
  Umbrella, Users,
  Video, Wallet, Wand, Wifi, Wrench, Zap,
  type LucideIcon,
} from "lucide-react";

export interface IconCatalogEntry {
  name: string;
  Icon: LucideIcon;
  keywords?: string[];
}

export const SPACE_ICON_CATALOG: IconCatalogEntry[] = [
  { name: "Briefcase", Icon: Briefcase, keywords: ["work", "business"] },
  { name: "Building", Icon: Building, keywords: ["office", "company"] },
  { name: "Building2", Icon: Building2, keywords: ["office", "skyscraper"] },
  { name: "BookOpen", Icon: BookOpen, keywords: ["knowledge", "docs"] },
  { name: "Beaker", Icon: Beaker, keywords: ["lab", "experiment"] },
  { name: "Brain", Icon: Brain, keywords: ["research", "ai"] },
  { name: "Bug", Icon: Bug, keywords: ["issue", "qa"] },
  { name: "Calculator", Icon: Calculator, keywords: ["finance", "math"] },
  { name: "Calendar", Icon: Calendar, keywords: ["schedule", "events"] },
  { name: "Camera", Icon: Camera, keywords: ["photo", "media"] },
  { name: "Car", Icon: Car, keywords: ["transport"] },
  { name: "ChartBar", Icon: ChartBar, keywords: ["analytics"] },
  { name: "ChartLine", Icon: ChartLine, keywords: ["analytics", "trends"] },
  { name: "ChartPie", Icon: ChartPie, keywords: ["analytics"] },
  { name: "Cloud", Icon: Cloud, keywords: ["infra"] },
  { name: "Code", Icon: Code, keywords: ["engineering", "dev"] },
  { name: "Compass", Icon: Compass, keywords: ["explore", "direction"] },
  { name: "Cpu", Icon: Cpu, keywords: ["engineering", "hardware"] },
  { name: "CreditCard", Icon: CreditCard, keywords: ["billing", "payments"] },
  { name: "Database", Icon: Database, keywords: ["data", "backend"] },
  { name: "DollarSign", Icon: DollarSign, keywords: ["finance", "money"] },
  { name: "Dumbbell", Icon: Dumbbell, keywords: ["fitness", "wellness"] },
  { name: "Factory", Icon: Factory, keywords: ["operations", "manufacturing"] },
  { name: "Flag", Icon: Flag, keywords: ["milestone", "goal"] },
  { name: "FileText", Icon: FileText, keywords: ["docs", "content"] },
  { name: "Film", Icon: Film, keywords: ["video", "media"] },
  { name: "Gauge", Icon: Gauge, keywords: ["performance", "metric"] },
  { name: "Gem", Icon: Gem, keywords: ["premium", "value"] },
  { name: "Gift", Icon: Gift, keywords: ["rewards", "kudos"] },
  { name: "Globe", Icon: Globe, keywords: ["global", "international"] },
  { name: "GraduationCap", Icon: GraduationCap, keywords: ["learning", "training"] },
  { name: "Hammer", Icon: Hammer, keywords: ["build", "construction"] },
  { name: "HardHat", Icon: HardHat, keywords: ["operations", "safety"] },
  { name: "Headphones", Icon: Headphones, keywords: ["support", "audio"] },
  { name: "Heart", Icon: Heart, keywords: ["wellness", "people"] },
  { name: "Home", Icon: Home, keywords: ["dashboard"] },
  { name: "Hospital", Icon: Hospital, keywords: ["healthcare"] },
  { name: "ImageIcon", Icon: ImageIcon, keywords: ["media", "design"] },
  { name: "Inbox", Icon: Inbox, keywords: ["mail", "queue"] },
  { name: "Key", Icon: Key, keywords: ["access", "security"] },
  { name: "Languages", Icon: Languages, keywords: ["translation", "localization"] },
  { name: "Laptop", Icon: Laptop, keywords: ["it", "devices"] },
  { name: "Layers", Icon: Layers, keywords: ["stack", "design"] },
  { name: "Library", Icon: Library, keywords: ["knowledge", "books"] },
  { name: "Lightbulb", Icon: Lightbulb, keywords: ["ideas"] },
  { name: "LinkIcon", Icon: LinkIcon, keywords: ["connections"] },
  { name: "MapPin", Icon: MapPin, keywords: ["location", "place"] },
  { name: "Megaphone", Icon: Megaphone, keywords: ["marketing", "announcements"] },
  { name: "MessageCircle", Icon: MessageCircle, keywords: ["chat", "comms"] },
  { name: "Mic", Icon: Mic, keywords: ["audio", "podcast"] },
  { name: "Monitor", Icon: Monitor, keywords: ["it", "screens"] },
  { name: "Mountain", Icon: Mountain, keywords: ["goals", "outdoors"] },
  { name: "Music", Icon: Music, keywords: ["media"] },
  { name: "Newspaper", Icon: Newspaper, keywords: ["press", "news"] },
  { name: "Notebook", Icon: Notebook, keywords: ["notes"] },
  { name: "Package", Icon: Package, keywords: ["shipping", "ops"] },
  { name: "Palette", Icon: Palette, keywords: ["design"] },
  { name: "Paperclip", Icon: Paperclip, keywords: ["attachments"] },
  { name: "Pen", Icon: Pen, keywords: ["writing"] },
  { name: "PenTool", Icon: PenTool, keywords: ["design"] },
  { name: "Phone", Icon: Phone, keywords: ["calls", "support"] },
  { name: "Plane", Icon: Plane, keywords: ["travel"] },
  { name: "Plug", Icon: Plug, keywords: ["integrations"] },
  { name: "Printer", Icon: Printer, keywords: ["office"] },
  { name: "Puzzle", Icon: Puzzle, keywords: ["solutions"] },
  { name: "Radio", Icon: Radio, keywords: ["broadcast"] },
  { name: "Receipt", Icon: Receipt, keywords: ["accounting"] },
  { name: "Rocket", Icon: Rocket, keywords: ["launch", "growth"] },
  { name: "Scale", Icon: Scale, keywords: ["legal"] },
  { name: "Scissors", Icon: Scissors, keywords: ["edit"] },
  { name: "Server", Icon: Server, keywords: ["infra"] },
  { name: "Settings", Icon: Settings, keywords: ["admin"] },
  { name: "Shield", Icon: Shield, keywords: ["security", "trust"] },
  { name: "ShoppingCart", Icon: ShoppingCart, keywords: ["ecommerce"] },
  { name: "Sparkles", Icon: Sparkles, keywords: ["ai", "magic"] },
  { name: "Star", Icon: Star, keywords: ["favorite"] },
  { name: "Sun", Icon: Sun, keywords: ["energy"] },
  { name: "Target", Icon: Target, keywords: ["goals", "kpi"] },
  { name: "Telescope", Icon: Telescope, keywords: ["research", "vision"] },
  { name: "TestTube", Icon: TestTube, keywords: ["qa", "research"] },
  { name: "Ticket", Icon: Ticket, keywords: ["support", "events"] },
  { name: "TreePine", Icon: TreePine, keywords: ["nature", "sustainability"] },
  { name: "TrendingUp", Icon: TrendingUp, keywords: ["growth", "analytics"] },
  { name: "Trophy", Icon: Trophy, keywords: ["wins", "kudos"] },
  { name: "Truck", Icon: Truck, keywords: ["shipping", "logistics"] },
  { name: "Tv", Icon: Tv, keywords: ["media"] },
  { name: "Umbrella", Icon: Umbrella, keywords: ["benefits", "protection"] },
  { name: "Users", Icon: Users, keywords: ["team", "people", "hr"] },
  { name: "Video", Icon: Video, keywords: ["media", "meetings"] },
  { name: "Wallet", Icon: Wallet, keywords: ["finance"] },
  { name: "Wand", Icon: Wand, keywords: ["ai", "magic"] },
  { name: "Wifi", Icon: Wifi, keywords: ["it"] },
  { name: "Wrench", Icon: Wrench, keywords: ["maintenance", "ops"] },
  { name: "Zap", Icon: Zap, keywords: ["fast", "ai"] },
];

const ICON_LOOKUP: Record<string, LucideIcon> = SPACE_ICON_CATALOG.reduce(
  (acc, entry) => {
    acc[entry.name] = entry.Icon;
    return acc;
  },
  {} as Record<string, LucideIcon>,
);

export function getSpaceIcon(name: string | null | undefined): LucideIcon | null {
  if (!name) return null;
  return ICON_LOOKUP[name] ?? null;
}

export const SPACE_COLOR_PALETTE: { name: string; hex: string }[] = [
  { name: "Red", hex: "#EB4D4B" },
  { name: "Orange", hex: "#F59E0B" },
  { name: "Amber", hex: "#FBBF24" },
  { name: "Green", hex: "#10B981" },
  { name: "Teal", hex: "#14B8A6" },
  { name: "Cyan", hex: "#06B6D4" },
  { name: "Blue", hex: "#3B82F6" },
  { name: "Indigo", hex: "#6366F1" },
  { name: "Violet", hex: "#8B5CF6" },
  { name: "Pink", hex: "#EC4899" },
  { name: "Slate", hex: "#64748B" },
];
