#!/usr/bin/env bash
# Verify a commit the way production will build it, in a clean worktree.
#
# WHY EVERY STEP IS HERE. Six deploys failed before this script existed, each
# for something a local `tsc` could not see:
#   - a commit that imported modules a selective commit had excluded
#   - a route folder with no entry in the proxy allowlist (served the
#     marketing site on the app host, with no error anywhere)
#   - a schema column with no migration (every read of that model threw)
#   - and, the reason `prisma generate` is below: the worktree's generated
#     client is NOT regenerated by `git checkout`. On 2026-09-21 the gate
#     type-checked a Sep 21 commit against a Sep 19 client and reported a
#     failure that did not exist. The same staleness can hide a REAL failure,
#     which is worse.
#
# Usage: scripts/verify-commit.sh <sha> [worktree-dir]
set -euo pipefail
SHA="${1:?usage: verify-commit.sh <sha> [dir]}"
DIR="${2:-/tmp/workwrk-verify}"
REPO="$(git rev-parse --show-toplevel)"

echo "==> worktree at $DIR on $SHA"
# PRUNE FIRST, because a worktree REGISTRATION outlives its directory.
#
# $DIR defaults under /tmp, which the OS cleans out. When the directory goes
# but git's registration stays, the test below sees no .git and takes the
# `worktree add` branch, and git refuses with "already registered" and exit
# 128. The gate then died on its very first step with nothing but the banner
# printed, which reads exactly like a build failure and is not one.
#
# `prune` drops registrations whose directory is missing and is a no-op
# otherwise, so it costs nothing on the common path.
#
# NOT `prune -q`: this git does not have that switch, and the `|| true` that
# was here swallowed the usage error, so the prune silently never ran. A
# guard that cannot fail cannot help.
git worktree prune
if [ -d "$DIR/.git" ] || [ -f "$DIR/.git" ]; then
  git -C "$DIR" fetch -q "$REPO" main 2>/dev/null || true
  git -C "$DIR" checkout -q --detach "$SHA"
  git -C "$DIR" clean -qfd
else
  git worktree add -q --detach "$DIR" "$SHA" || {
    echo "COULD NOT CREATE THE WORKTREE at $DIR. Registrations now:"
    git worktree list
    exit 1
  }
fi
cd "$DIR"

# node_modules: reuse if present (npm ci is minutes), but ALWAYS regenerate the
# Prisma client, because it is generated from the schema of whatever commit was
# checked out last, not this one.
[ -d node_modules ] || npm ci
echo "==> prisma generate (against THIS commit's schema)"
npx prisma generate >/dev/null

echo "==> imports resolve inside the commit"
python3 - "$SHA" <<'PY'
import subprocess,re,sys
sha=sys.argv[1]
files=subprocess.run(['git','ls-tree','-r','--name-only',sha],capture_output=True,text=True).stdout.split('\n'); fs=set(files)
def ok(m):
    if m.startswith('@/generated/'): return True
    b='src/'+m[2:]
    return any(b+e in fs for e in ('.ts','.tsx','.js','.jsx','/index.ts','/index.tsx','.json','.css','.mjs',''))
bad={}
for f in [x for x in files if x.startswith('src/') and x.endswith(('.ts','.tsx'))]:
    s=subprocess.run(['git','show',f'{sha}:{f}'],capture_output=True,text=True).stdout
    for m in set(re.findall(r'from\s+"(@/[^"]+)"',s)):
        if not ok(m) and 'text-sm/y' not in m: bad.setdefault(f,set()).add(m)
if bad:
    for f,ms in sorted(bad.items()): print(f"   BROKEN {f} -> {', '.join(sorted(ms))}")
    raise SystemExit(1)
print("   ok, every @/ import resolves")
PY

echo "==> guards"
node scripts/check-app-prefixes.mjs
node scripts/check-schema-sql.mjs

# TYPE CHECK. NOTHING ELSE IN THE PIPELINE DOES ONE.
#
# CI runs prisma validate, the two guards and vitest. It does not run tsc.
# And `next build` under Turbopack does not type check either, which is the
# part that surprises people: a green build is not a green compile. So until
# this line existed, a real type error could pass the gate, pass CI, and ship.
#
# Found on 2026-09-22 while the Phase 4 deploy was in flight: four genuine
# errors in a Talk component (a `export { X as Y } from` re-export, which
# creates no local binding, followed by uses of the bare name, plus an icon
# dropped from an import while still rendered). Those would have been a
# ReferenceError in the message feed at runtime, not a build failure.
#
# It runs BEFORE the tests because it is much faster and its failures are
# more specific: a type error usually explains a test failure downstream.
echo "==> type check"
npx tsc --noEmit -p tsconfig.json > /tmp/verify-tsc.log 2>&1 || {
  echo "TYPE ERRORS:"; grep "error TS" /tmp/verify-tsc.log | head -30; exit 1;
}
echo "   ok, 0 type errors"

# THE TEST SUITE, INSIDE THE WORKTREE, AGAINST THE COMMIT'S OWN FILES.
#
# WHY THIS STEP EXISTS (added 2026-09-22, after it let two pushes through).
# The gate proved a commit BUILDS and that every `@/` import resolves inside
# it, and reported PASS on faf276e3 and e1f44924. CI then failed both, and
# the Deploy job is gated on CI, so it was skipped: two commits reported as
# shipped were not on the box at all.
#
# The cause was a dependency the import scan cannot see. A test reads a
# source file BY PATH:
#
#   marketing-tokens.test.ts:169  readFileSync(OG_ROUTE)   <- api/og/receipt
#
# That file was not in the path-scoped marketing commit. It existed
# untracked on my disk, so the local `vitest run` passed; it did not exist
# in the commit, so CI could not open it. A `readFileSync` of a route is not
# an import and never appears in an import graph.
#
# The lesson generalises past this one file: the ONLY way to know a commit's
# tests pass is to run them against the commit's own tree, which is what the
# worktree already is. Building is not enough, because a test that reads the
# repo is testing the repo, not the bundle.
#
# TZ=UTC to match CI. Note this still runs on the local Node (24) while CI
# and production are Node 20, so it cannot catch a Node-20-only failure; see
# the ICU midnight bug in reference_workwrk_ci_node20_traps.
echo "==> unit tests (the commit's own tree)"
TZ=UTC npx vitest run > /tmp/verify-test.log 2>&1 || {
  echo "TESTS FAILED. Last 40 lines:"; sed 's/\x1b\[[0-9;]*m//g' /tmp/verify-test.log | tail -40; exit 1;
}
sed 's/\x1b\[[0-9;]*m//g' /tmp/verify-test.log | grep -E "^ *(Test Files|Tests) " || true

echo "==> production build"
rm -rf .next
NODE_OPTIONS=--max-old-space-size=3072 npx next build > /tmp/verify-build.log 2>&1 || {
  echo "BUILD FAILED. Last 40 lines:"; sed 's/\x1b\[[0-9;]*m//g' /tmp/verify-build.log | tail -40; exit 1;
}
[ -f .next/BUILD_ID ] || { echo "NO BUILD_ID despite exit 0"; exit 1; }
echo "==> PASS  BUILD_ID $(cat .next/BUILD_ID)"
