#!/usr/bin/env bash
# Verify a commit the way production will build it, in a clean worktree.
#
# WHY EVERY STEP IS HERE. Six deploys failed before this script existed, each
# for something a local `tsc` could not see:
#   - a commit that imported modules a selective commit had excluded
#   - a route folder with no entry in the proxy allowlist (served the
#     marketing site on the app host, with no error anywhere)
#   - a schema column with no migration (every read of that model threw)
#   - and, the reason `prisma generate` is below: the worktree's generated
#     client is NOT regenerated by `git checkout`. On 2026-09-21 the gate
#     type-checked a Sep 21 commit against a Sep 19 client and reported a
#     failure that did not exist. The same staleness can hide a REAL failure,
#     which is worse.
#
# Usage: scripts/verify-commit.sh <sha> [worktree-dir]
set -euo pipefail
SHA="${1:?usage: verify-commit.sh <sha> [dir]}"
DIR="${2:-/tmp/workwrk-verify}"
REPO="$(git rev-parse --show-toplevel)"

echo "==> worktree at $DIR on $SHA"
if [ -d "$DIR/.git" ] || [ -f "$DIR/.git" ]; then
  git -C "$DIR" fetch -q "$REPO" main 2>/dev/null || true
  git -C "$DIR" checkout -q --detach "$SHA"
  git -C "$DIR" clean -qfd
else
  git worktree add -q --detach "$DIR" "$SHA"
fi
cd "$DIR"

# node_modules: reuse if present (npm ci is minutes), but ALWAYS regenerate the
# Prisma client, because it is generated from the schema of whatever commit was
# checked out last, not this one.
[ -d node_modules ] || npm ci
echo "==> prisma generate (against THIS commit's schema)"
npx prisma generate >/dev/null

echo "==> imports resolve inside the commit"
python3 - "$SHA" <<'PY'
import subprocess,re,sys
sha=sys.argv[1]
files=subprocess.run(['git','ls-tree','-r','--name-only',sha],capture_output=True,text=True).stdout.split('\n'); fs=set(files)
def ok(m):
    if m.startswith('@/generated/'): return True
    b='src/'+m[2:]
    return any(b+e in fs for e in ('.ts','.tsx','.js','.jsx','/index.ts','/index.tsx','.json','.css','.mjs',''))
bad={}
for f in [x for x in files if x.startswith('src/') and x.endswith(('.ts','.tsx'))]:
    s=subprocess.run(['git','show',f'{sha}:{f}'],capture_output=True,text=True).stdout
    for m in set(re.findall(r'from\s+"(@/[^"]+)"',s)):
        if not ok(m) and 'text-sm/y' not in m: bad.setdefault(f,set()).add(m)
if bad:
    for f,ms in sorted(bad.items()): print(f"   BROKEN {f} -> {', '.join(sorted(ms))}")
    raise SystemExit(1)
print("   ok, every @/ import resolves")
PY

echo "==> guards"
node scripts/check-app-prefixes.mjs
node scripts/check-schema-sql.mjs

echo "==> production build"
rm -rf .next
NODE_OPTIONS=--max-old-space-size=3072 npx next build > /tmp/verify-build.log 2>&1 || {
  echo "BUILD FAILED. Last 40 lines:"; sed 's/\x1b\[[0-9;]*m//g' /tmp/verify-build.log | tail -40; exit 1;
}
[ -f .next/BUILD_ID ] || { echo "NO BUILD_ID despite exit 0"; exit 1; }
echo "==> PASS  BUILD_ID $(cat .next/BUILD_ID)"
