-- Extend TagEntityType so the polymorphic tag filter can target
-- approval queues, recruiting, and procurement rows.

ALTER TYPE "TagEntityType" ADD VALUE IF NOT EXISTS 'TIME_OFF_REQUEST';
ALTER TYPE "TagEntityType" ADD VALUE IF NOT EXISTS 'TIMESHEET';
ALTER TYPE "TagEntityType" ADD VALUE IF NOT EXISTS 'POLICY';
ALTER TYPE "TagEntityType" ADD VALUE IF NOT EXISTS 'PROCESS_RUN';
ALTER TYPE "TagEntityType" ADD VALUE IF NOT EXISTS 'ANNOUNCEMENT';
ALTER TYPE "TagEntityType" ADD VALUE IF NOT EXISTS 'DEPARTMENT';
ALTER TYPE "TagEntityType" ADD VALUE IF NOT EXISTS 'ROLE';
ALTER TYPE "TagEntityType" ADD VALUE IF NOT EXISTS 'VENDOR';
ALTER TYPE "TagEntityType" ADD VALUE IF NOT EXISTS 'PURCHASE_ORDER';
ALTER TYPE "TagEntityType" ADD VALUE IF NOT EXISTS 'INVOICE';
ALTER TYPE "TagEntityType" ADD VALUE IF NOT EXISTS 'CANDIDATE';
ALTER TYPE "TagEntityType" ADD VALUE IF NOT EXISTS 'JOB';
